name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
    MONGO_URI: 'mongodb+srv://cluster0.lgcvdln.mongodb.net/mydb'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        env:
          BUILD_NAME: 'solarsystem'
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: JFrog CLI setup 🐸
          uses: jfrog/setup-jfrog-cli@v4
          env:
            JF_URL: ${{ vars.JF_URL }}
            JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
            JF_USER: ${{ vars.JF_USER }}
            JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
            NPM_JF_RT_REPO: ${{ vars.NPM_JF_RT_REPO }}
        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
              node-version: 20
      
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        # - name: Archive Test Result
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: Mocha-Test-Result
        #     path: test-results.xml
