name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: 'mongodb+srv://cluster0.vbdphob.mongodb.net/mydb'
  MONGO_USERNAME: nagaraju
  MONGO_PASSWORD: nagaraju
    
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
      
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        # - name: Archive Test Result
        #   uses: actions/upload-artifact@v3
        #   with:
        #     name: Mocha-Test-Result
        #     path: test-results.xml